defmodule Homework.Companies.Company do
  @moduledoc """
  Ecto schema for Company
  """

  use Ecto.Schema
  import Ecto.Changeset

  @type t :: %__MODULE__{
          __meta__: Ecto.Schema.Metadata.t(),
          id: Ecto.UUID.t(),
          credit_line: non_neg_integer(),
          name: String.t(),
          inserted_at: NaiveDateTime.t(),
          updated_at: NaiveDateTime.t()
        }

  @autogenerated_fields ~w(id inserted_at updated_at)a
  @required_fields ~w(credit_line name)a

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "companies" do
    field(:credit_line, :integer)
    field(:name, :string)

    timestamps()
  end

  @doc false
  def changeset(company, attrs) do
    company
    |> cast(attrs, all_fields() -- @autogenerated_fields)
    |> validate_required(@required_fields)
    |> validate_number(:credit_line, greater_than_or_equal_to: 0)
  end

  @spec all_fields :: list(atom)
  defp all_fields, do: __MODULE__.__schema__(:fields)
end
